import {ReactNode} from 'react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Head from 'next/head'

const BaseLayout = ({ children }: { children: ReactNode}) => {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            <main className="max-w-7xl mx-auto my-6 sm:px-6 lg:px-8">
                {children}
            </main>
            <Footer />
        </>
    )
}

export default BaseLayout
